# Documentation for this file can be found at:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - area/dependency
    commit-message:
      prefix: chore
      include: scope
